PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX spec: <http://uibk.ac.at/se/bimclipse/reasoning/specification#>
                            
SELECT ?subject ?subjectId ?check ?checkResult
WHERE {
	?check rdf:type spec:Check .
	?subject ?check ?checkResult .
	?subject spec:hasId ?subjectId .
}